name: 環境構築
description: 環境構築・設定周りのタスク
title: '🔧 environment: '
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 環境構築の概要を記載してください
      required: true
  - type: input
    id: done
    attributes:
      label: 完了予定日
      description: 新機能の開発完了予定日を記載してください
      type: date
      required: true
  - type: textarea
    id: todo
    attributes:
      label: タスク
      description: タスクを記載してください
      value: |
        - [ ]
        - [ ]
      validation:
        required: true
  - type: textarea
    id: module
    attributes:
      label: 追加したモジュール
      description: 追加するモジュールを記載してください
      value: |
        -
        -
  - type: textarea
    id: note
    attributes:
      label: 備考
      description: 環境構築・設定に関する備考を記載してください
      placeholder:
