import { ZenOldMincho, ZenKakuGothicAnitique } from '@/styles/font'

import { NavigationBar } from './_components/Common/NavigationBar/NavigationBarContainer'

import type { Metadata } from 'next'

import '@/styles/tailwind.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${ZenOldMincho.variable} ${ZenKakuGothicAnitique.variable}`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  )
}
